### ISSUE TITLE
There was a problem generating

### ISSUE THREAD

**Issue by xiaoxiaodadada** [THUDM/Inf-DiT#14]
I have entered a low-resolution image according to the format, but it gives an error
Traceback (most recent call last):
  File "/data1/zhuyifan/Inf-DiT-main/generate_t2i_sr.py", line 210, in <module>
    main(args)
  File "/data1/zhuyifan/Inf-DiT-main/generate_t2i_sr.py", line 139, in main
    h, w = lr_image.shape[-2:]
AttributeError: 'Image' object has no attribute 'shape'.

**Comment by xiaoxiaodadada** [comment]
NumPy version mismatch, solved
